# Dependabot version updates configuration
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for client
  - package-ecosystem: "pip"
    directory: "/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"

  # Maintain dependencies for server
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"
