apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo.client" . }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
    app: {{ include "echo.client" . }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.client.nodePort }}
      port: {{ .Values.client.port }}
      protocol: TCP
      targetPort: {{ .Values.client.port }}
  selector:
    {{- include "echo.selectorLabels" . | nindent 4 }}
    app: {{ include "echo.client" . }}
