apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo.server" . }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
    app: {{ include "echo.server" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
  selector:
    {{- include "echo.selectorLabels" . | nindent 4 }}
    app: {{ include "echo.server" . }}
