name: Echo Server Docker Image

on:
  push:
    branches:
      - master
    paths:
      - server/**
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd server && make
